language: php
php:
- 7.2
addons:
  ssh_known_hosts: 165.227.197.233
script:
- echo "teste"
deploy:
  provider: script
  skip_cleanup: true
  script: echo "teste"
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_f0ca5aa8b9d3_key -iv $encrypted_f0ca5aa8b9d3_iv
  -in deploy.enc -out /tmp/deploy -d
